version: '2'

volumes:

    mysql-data-debts:
      driver: local
    mysql-score:
      driver: local
    mysql-document-events:
      driver: local

services:

  mysql:
    image: mysql
    hostname: mysql
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=db_a
       - MYSQL_USER=my_user
       - MYSQL_PASSWORD=my_pass
    volumes:
      - mysql-data-debts:/var/lib/mysql

  mysql_b:
    image: mysql
    hostname: mysql_b
    restart: always
    container_name: mysql_b
    ports:
      - 3307:3307
    environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=db_b
       - MYSQL_USER=my_user
       - MYSQL_PASSWORD=my_pass
    volumes:
      - mysql-score:/var/lib/mysql_b

  mysql_c:
    image: mysql
    hostname: mysql_c
    restart: always
    container_name: mysql_c
    ports:
      - 3308:3308
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_c
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_pass
    volumes:
      - mysql-document-events:/var/lib/mysql_c

  data-debts:
    restart: 'no'
    container_name: data-debts
    volumes:
      - ./data_debts:/app
    build:
      context: ./data_debts
      dockerfile: Dockerfile
    depends_on:
      - mysql
    env_file:
      - ./data_debts/.env
    links:
      - mysql
    expose:
      - 5000
    ports:
      - 5000:5000

  score:
    restart: 'no'
    container_name: score
    volumes:
      - ./score:/app
    build:
      context: ./score
      dockerfile: Dockerfile
    depends_on:
      - mysql_b
    env_file:
      - ./score/.env
    links:
      - mysql_b
    expose:
      - 5000
    ports:
      - 5000:5000

  document-events:
    restart: 'no'
    container_name: document-events
    volumes:
      - ./document_events:/app
    build:
      context: ./document_events
      dockerfile: Dockerfile
    depends_on:
      - mysql_c
    env_file:
      - ./document_events/.env
    links:
      - mysql_c
    expose:
      - 5000
    ports:
      - 5000:5000
