version: '2'

volumes:

    mysql-data-debts:
      driver: local


services:

  mysql:
    image: mysql
    hostname: mysql
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    environment:
       - MYSQL_ROOT_PASSWORD=secret
       - MYSQL_DATABASE=db_a
       - MYSQL_USER=admin
       - MYSQL_PASSWORD=passwd
    volumes:
      - mysql-data-debts:/var/lib/mysql


  data-debts:
    restart: 'no'
    container_name: data-debts
    volumes:
      - ./data_debts:/app
    build:
      context: ./data_debts
      dockerfile: Dockerfile
    depends_on:
      - mysql
    env_file:
      - ./data_debts/.env
    links:
      - mysql
    expose:
      - 5000
    ports:
      - 5000:5000
